import "@/app/global.css"
import Header from "@/components/layouts/header/header"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <head>
        <title>BCS - Business Card Scanner -</title>
      </head>
      <body>
        <Header></Header>
        <div className="content">
          {children}
        </div>
      </body>
    </html>
  )
}
